Changes: (#9)
* extract_roles.js to provide description of permissions and roles in API spec. Every description contains now a <meta> tag which is replaced by proper role description. The processed *.raml files are copied to build directory.
* Added Makefile rules to process all *.raml files
* Added "hidden" API path in users.raml: /activation and POST:/v1/api/users
* Added description of Authorization roles in auth.raml
* Added test target in Makefile for testing API building
* Added test target for API building in Gruntfile.js
* Fixed several errors in API description
* Added doc/api/*.js to jshint tests in Gruntfile.js
* Fixed jshint complaints of doc/api/*.js files
* Cleanup of program style: Replaced underscore variable naming with CamelCase style

diff --git a/public-interface/doc/api/Makefile b/public-interface/doc/api/Makefile
--- a/public-interface/doc/api/Makefile
+++ b/public-interface/doc/api/Makefile
@@ -26,6 +26,7 @@ SCHEMA_PATH  = ../../lib/schema-validator/schemas
 SCHEMA_FILES = $(wildcard ${SCHEMA_PATH}/*.json)
 ERRORS_FILE  = ../../engine/res/errors.js
 RAML_FILES   = $(wildcard *.raml)
+RAML_BUILD_FILES = $(patsubst %.raml,build/%.raml,${RAML_FILES})  
 HTML_FILE    = api.html
 RAML2HTML    = ./node_modules/raml2html/bin/raml2html
 
@@ -39,7 +40,7 @@ RAML2HTML    = ./node_modules/raml2html/bin/raml2html
 	@npm install
 	@touch $@
 
-${HTML_FILE}: .init .create_schemas .create_error_files $(TARGET:.html=.raml) ${RAML_FILES}
+${HTML_FILE}: .init .create_schemas .create_error_files $(TARGET:.html=.raml) ${RAML_BUILD_FILES}
 
 .create_schemas: ${SCHEMA_FILES}
 	@$(call msg,"Creating Schema files ...");
@@ -52,11 +53,15 @@ ${HTML_FILE}: .init .create_schemas .create_error_files $(TARGET:.html=.raml) ${
 	@touch $@
 
 
+build/%.raml: %.raml
+	@$(call msg,"Inserting roles in RAML files ...");
+	node ./extract_roles.js $<
+
 all: ${HTML_FILE}
 
 clean:
 	@$(call msg,"Cleaning ..."); 
-	@rm -f .init .create_schemas *.html .create_error_files
+	@rm -f .init .create_schemas *.html .create_error_files .extract_roles
 	@rm -rf build
 	@rm -f ../../dashboard/public/api.html
 
@@ -65,8 +70,22 @@ install: ${HTML_FILE}
 
 distclean: clean
 
-
-
+test: clean all
+	@tput setaf 2 && echo -n "Success:" && tput sgr0 && echo " Built API successfully."
+	@echo "Test whether meta-tags processed properly."
+	@if (grep "<meta name=" build/*.raml) \
+		then \
+			tput setaf 1 && echo -n "Fail:" && tput sgr0 && echo " <meta> tags still found in processed *.raml files"; exit 1; \
+			else tput setaf 2 && echo -n "Success:" && tput sgr0 && echo " Test successful: No <meta> tags found in raml files";\
+	fi
+	@echo "Test whether ${HTML_FILE} contains something."
+	@if [ ! -s ${HTML_FILE} ]; \
+		then \
+			rm ${HTML_FILE};\
+			tput setaf 1 && echo -n "Fail:" &&  tput sgr0 && echo " HTML file empty";\
+			exit 1; \
+		else tput setaf 2 && echo -n "Success:" && tput sgr0 && echo " HTML file size non-zero";\
+	fi
 
 #----------------------------------------------------------------------------------------------------------------------
 # helper functions
